export const CARD_WIDTH = 223;
export const CARD_HEIGHT = 324;
export const CARD_ASPECT_RATIO = CARD_WIDTH / CARD_HEIGHT;
export const DEFAULT_CARD_SIZE_PERCENT = 12;
export const PLAYER_POSITIONS = ["N", "E", "S", "W"] as const;
export const W_WIDTH = window.innerWidth;
export const W_HEIGHT = window.innerHeight;

export const DECK = [
  "3s",
  "3c",
  "3d",
  "3h",
  "4s",
  "4c",
  "4d",
  "4h",
  "5s",
  "5c",
  "5d",
  "5h",
  "6s",
  "6c",
  "6d",
  "6h",
  "7s",
  "7c",
  "7d",
  "7h",
  "8s",
  "8c",
  "8d",
  "8h",
  "9s",
  "9c",
  "9d",
  "9h",
  "Ts",
  "Tc",
  "Td",
  "Th",
  "Js",
  "Jc",
  "Jd",
  "Jh",
  "Qs",
  "Qc",
  "Qd",
  "Qh",
  "Ks",
  "Kc",
  "Kd",
  "Kh",
  "As",
  "Ac",
  "Ad",
  "Ah",
  "2s",
  "2c",
  "2d",
  "2h",
] as const;

export const RANK_ORDER = ["3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A", "2"];
export const SUIT_ORDER = ["s", "c", "d", "h"];
export const AVATAR_NAMES = [
  "Mary Baker",
  "Amelia Earhart",
  "Mary Roebling",
  "Sarah Winnemucca",
  "Margaret Brent",
  "Lucy Stone",
  "Mary Edwards",
  "Margaret Chase",
  "Mahalia Jackson",
  "Maya Angelou",
  "Margaret Bourke",
  "Eunice Kennedy",
  "Carrie Chapman",
  "Elizabeth Peratrovich",
  "Alicia Dickerson",
  "Daisy Gatson",
  "Emma Willard",
  "Amelia Boynton",
  "Maria Mitchell",
  "Sojourner Truth",
  "Willa Cather",
  "Coretta Scott",
  "Harriet Tubman",
  "Fabiola Cabeza",
  "Sacagawea",
  "Esther Martinez",
  "Elizabeth Cady",
  "Bessie Coleman",
  "Ma Rainey",
  "Julia Ward",
  "Irene Morgan",
  "Babe Didrikson",
  "Lyda Conley",
  "Annie Dodge",
  "Maud Nathan",
  "Betty Ford",
  "Rosa Parks",
  "Susan La",
  "Gertrude Stein",
  "Wilma Mankiller",
  "Grace Hopper",
  "Jane Addams",
  "Katharine Graham",
  "Florence Chadwick",
  "Zora Neale",
  "Wilma Rudolph",
  "Annie Jump",
  "Mother Frances",
  "Jovita Idár",
  "Maggie L",
  "Henrietta Swan",
  "Jane Cunningham",
  "Victoria Woodhull",
  "Helen Keller",
  "Patsy Takemoto",
  "Chien-Shiung",
  "Dorothea Dix",
  "Margaret Sanger",
  "Alice Paul",
  "Frances Willard",
  "Sally Ride",
  "Juliette Gordon",
  "Queen Lili",
  "Katharine Lee",
  "Harriet Beecher",
  "Felisa Rincon",
  "Hetty Green",
  "Belva Lockwood",
  "Biddy Mason",
  "Ida B",
  "Eleanor Roosevelt",
  "Maria Goeppert",
  "Phillis Wheatley",
  "Mary Harris",
  "Fannie Lou",
  "Rosalyn Yalow",
  "Susan B",
  "Clara Barton",
  "Lady Deborah",
  "Jane Johnston",
  "Alice Childress",
  "Georgia O",
  "Rebecca Crumpler",
  "Anne Bradstreet",
  "Elizabeth Blackwell",
  "Christa McAuliffe",
  "Edmonia Lewis",
  "Nellie Bly",
  "Mary Cassatt",
  "Pauli Murray",
  "Ellen Swallow",
  "Hedy Lamarr",
  "Pearl Kendrick",
  "Abigail Adams",
  "Margaret Fuller",
  "Emma Lazarus",
  "Marian Anderson",
  "Virginia Apgar",
  "Mary Walton",
] as const;
